### ISSUE TITLE
Benchmark parameters

### ISSUE THREAD

**Issue by olisicky** [MFajcik/benczechmark-leaderboard#1]
Hi!

Thank you for CZ benchmarks.  I was not able to find the setup for each benchmark you've already evaluated e.g., few-shot number to reproduce the results and be able to compare my models. The examples show number 3 should I expect the same setup for each bench? 

Thank you! 

Ondřej

**Comment by MFajcik** [comment]
Hello @olisicky ,

these can be determined from jobscripts in [our lm harness repo](https://github.com/DCGM/lm-evaluation-harness/tree/main/jobs), not here. But it's not that all parameters are set in one place. Let me help you with example:

For example:

aya23 jobscript is here:
https://github.com/DCGM/lm-evaluation-harness/blob/main/jobs/scripts/submit/models_M/eval_aya23_35B_instruct_smartt.sh

Following the fire script, this executes `./jobs/scripts/models/eval_M_accelerate.sh`
located here:
https://github.com/DCGM/lm-evaluation-harness/blob/main/jobs/scripts/models/eval_M_accelerate.sh

`NUM_FEWSHOT=0 ` is passed only for tasks, where we want to be 100% sure, there is no n-shot (such as language modeling). Otherwise it is empty, and task default n-shot is used.

Here the lm harness call is at the end of the script.

Here you can find the max_length for the model, and other parameters (truncate strategy, whether to normalize logprobs etc).

Some other parameters are directly part of the dataset configuration. You can find all configurations here:
https://github.com/DCGM/lm-evaluation-harness/tree/main/lm_eval/tasks/benczechmark


n-shot for all tasks in benczechmark is specifically  set in
https://github.com/DCGM/lm-evaluation-harness/blob/main/lm_eval/tasks/benczechmark/templates/n_shot_yaml

And then is further included by other scripts such as 
https://github.com/DCGM/lm-evaluation-harness/blob/main/lm_eval/tasks/benczechmark/templates/multichoice/multi_class_template_yaml

Further included by other scripts such as 
https://github.com/DCGM/lm-evaluation-harness/blob/main/lm_eval/tasks/benczechmark/templates/multichoice/multi_class_template_wtrain_yaml

Further included by dataset configs, such as here:
https://github.com/DCGM/lm-evaluation-harness/blob/main/lm_eval/tasks/benczechmark/benczechmark_snli.yaml

Let me know if you need help with further navigation.

>The examples show number 3 should I expect the same setup for each bench?

Everything except for language modeling was ran in 3-shot yes. To be comparable, also be sure to use smart truncation, and logP averaging (i.e., normalize_log_probs parameter.) for our lm harness (again, except for LM modeling, there we want to sum logprobs, to compute valid ppl).

**Comment by olisicky** [comment]
> Hello @olisicky ,
> 
> these can be determined from jobscripts in [our lm harness repo](https://github.com/DCGM/lm-evaluation-harness/tree/main/jobs), not here. But it's not that all parameters are set in one place. Let me help you with example:
> 
> For example:
> 
> aya23 jobscript is here: https://github.com/DCGM/lm-evaluation-harness/blob/main/jobs/scripts/submit/models_M/eval_aya23_35B_instruct_smartt.sh
> 
> Following the fire script, this executes `./jobs/scripts/models/eval_M_accelerate.sh` located here: https://github.com/DCGM/lm-evaluation-harness/blob/main/jobs/scripts/models/eval_M_accelerate.sh
> 
> `NUM_FEWSHOT=0 ` is passed only for tasks, where we want to be 100% sure, there is no n-shot (such as language modeling). Otherwise it is empty, and task default n-shot is used.
> 
> Here the lm harness call is at the end of the script.
> 
> Here you can find the max_length for the model, and other parameters (truncate strategy, whether to normalize logprobs etc).
> 
> Some other parameters are directly part of the dataset configuration. You can find all configurations here: https://github.com/DCGM/lm-evaluation-harness/tree/main/lm_eval/tasks/benczechmark
> 
> n-shot for all tasks in benczechmark is specifically set in https://github.com/DCGM/lm-evaluation-harness/blob/main/lm_eval/tasks/benczechmark/templates/n_shot_yaml
> 
> And then is further included by other scripts such as https://github.com/DCGM/lm-evaluation-harness/blob/main/lm_eval/tasks/benczechmark/templates/multichoice/multi_class_template_yaml
> 
> Further included by other scripts such as https://github.com/DCGM/lm-evaluation-harness/blob/main/lm_eval/tasks/benczechmark/templates/multichoice/multi_class_template_wtrain_yaml
> 
> Further included by dataset configs, such as here: https://github.com/DCGM/lm-evaluation-harness/blob/main/lm_eval/tasks/benczechmark/benczechmark_snli.yaml
> 
> Let me know if you need help with further navigation.

Okey, now I know where to look, thanks. It is quite hidden. I think you are using ENVs from scripts which are not in the repo (at least I have not found e.g., `TASKS.sh`) so it is hard to verify proper setup.
> > The examples show number 3 should I expect the same setup for each bench?
> 
> Everything except for language modeling was ran in 3-shot yes. To be comparable, also be sure to use smart truncation, and logP averaging (i.e., normalize_log_probs parameter.) for our lm harness (again, except for LM modeling, there we want to sum logprobs, to compute valid ppl).


Okey,  thank you!

Ondřej

**Comment by MFajcik** [comment]
> > Hello @olisicky ,
> > these can be determined from jobscripts in [our lm harness repo](https://github.com/DCGM/lm-evaluation-harness/tree/main/jobs), not here. But it's not that all parameters are set in one place. Let me help you with example:
> > For example:
> > aya23 jobscript is here: https://github.com/DCGM/lm-evaluation-harness/blob/main/jobs/scripts/submit/models_M/eval_aya23_35B_instruct_smartt.sh
> > Following the fire script, this executes `./jobs/scripts/models/eval_M_accelerate.sh` located here: https://github.com/DCGM/lm-evaluation-harness/blob/main/jobs/scripts/models/eval_M_accelerate.sh
> > `NUM_FEWSHOT=0 ` is passed only for tasks, where we want to be 100% sure, there is no n-shot (such as language modeling). Otherwise it is empty, and task default n-shot is used.
> > Here the lm harness call is at the end of the script.
> > Here you can find the max_length for the model, and other parameters (truncate strategy, whether to normalize logprobs etc).
> > Some other parameters are directly part of the dataset configuration. You can find all configurations here: https://github.com/DCGM/lm-evaluation-harness/tree/main/lm_eval/tasks/benczechmark
> > n-shot for all tasks in benczechmark is specifically set in https://github.com/DCGM/lm-evaluation-harness/blob/main/lm_eval/tasks/benczechmark/templates/n_shot_yaml
> > And then is further included by other scripts such as https://github.com/DCGM/lm-evaluation-harness/blob/main/lm_eval/tasks/benczechmark/templates/multichoice/multi_class_template_yaml
> > Further included by other scripts such as https://github.com/DCGM/lm-evaluation-harness/blob/main/lm_eval/tasks/benczechmark/templates/multichoice/multi_class_template_wtrain_yaml
> > Further included by dataset configs, such as here: https://github.com/DCGM/lm-evaluation-harness/blob/main/lm_eval/tasks/benczechmark/benczechmark_snli.yaml
> > Let me know if you need help with further navigation.
> 
> Okey, now I know where to look, thanks. It is quite hidden. I think you are using ENVs from scripts which are not in the repo (at least I have not found e.g., `TASKS.sh`) so it is hard to verify proper setup.
> 
> > > The examples show number 3 should I expect the same setup for each bench?
> > 
> > 
> > Everything except for language modeling was ran in 3-shot yes. To be comparable, also be sure to use smart truncation, and logP averaging (i.e., normalize_log_probs parameter.) for our lm harness (again, except for LM modeling, there we want to sum logprobs, to compute valid ppl).
> 
> Okey, thank you!
> 
> Ondřej

`TASKS.sh` is there, check out
https://github.com/DCGM/lm-evaluation-harness/tree/main/jobs

If there is some env setup missing, please keep me updated, because that is definitely a bug.

**Comment by olisicky** [comment]
> > > Hello @olisicky ,
> > > these can be determined from jobscripts in [our lm harness repo](https://github.com/DCGM/lm-evaluation-harness/tree/main/jobs), not here. But it's not that all parameters are set in one place. Let me help you with example:
> > > For example:
> > > aya23 jobscript is here: https://github.com/DCGM/lm-evaluation-harness/blob/main/jobs/scripts/submit/models_M/eval_aya23_35B_instruct_smartt.sh
> > > Following the fire script, this executes `./jobs/scripts/models/eval_M_accelerate.sh` located here: https://github.com/DCGM/lm-evaluation-harness/blob/main/jobs/scripts/models/eval_M_accelerate.sh
> > > `NUM_FEWSHOT=0 ` is passed only for tasks, where we want to be 100% sure, there is no n-shot (such as language modeling). Otherwise it is empty, and task default n-shot is used.
> > > Here the lm harness call is at the end of the script.
> > > Here you can find the max_length for the model, and other parameters (truncate strategy, whether to normalize logprobs etc).
> > > Some other parameters are directly part of the dataset configuration. You can find all configurations here: https://github.com/DCGM/lm-evaluation-harness/tree/main/lm_eval/tasks/benczechmark
> > > n-shot for all tasks in benczechmark is specifically set in https://github.com/DCGM/lm-evaluation-harness/blob/main/lm_eval/tasks/benczechmark/templates/n_shot_yaml
> > > And then is further included by other scripts such as https://github.com/DCGM/lm-evaluation-harness/blob/main/lm_eval/tasks/benczechmark/templates/multichoice/multi_class_template_yaml
> > > Further included by other scripts such as https://github.com/DCGM/lm-evaluation-harness/blob/main/lm_eval/tasks/benczechmark/templates/multichoice/multi_class_template_wtrain_yaml
> > > Further included by dataset configs, such as here: https://github.com/DCGM/lm-evaluation-harness/blob/main/lm_eval/tasks/benczechmark/benczechmark_snli.yaml
> > > Let me know if you need help with further navigation.
> > 
> > 
> > Okey, now I know where to look, thanks. It is quite hidden. I think you are using ENVs from scripts which are not in the repo (at least I have not found e.g., `TASKS.sh`) so it is hard to verify proper setup.
> > > > The examples show number 3 should I expect the same setup for each bench?
> > > 
> > > 
> > > Everything except for language modeling was ran in 3-shot yes. To be comparable, also be sure to use smart truncation, and logP averaging (i.e., normalize_log_probs parameter.) for our lm harness (again, except for LM modeling, there we want to sum logprobs, to compute valid ppl).
> > 
> > 
> > Okey, thank you!
> > Ondřej
> 
> `TASKS.sh` is there, check out https://github.com/DCGM/lm-evaluation-harness/tree/main/jobs
> 
> If there is some env setup missing, please keep me updated, because that is definitely a bug.

VSCode was not able to find the file and I am personally blind, sorry!

Thanks

Ondřej
